"""Unit tests for the auth service — pure functions, no database.

These tests were generated by asking the agent:
"Write unit tests for the auth service. Cover password hashing,
session tokens, and session expiry."

All 7 pass. 100% coverage. But most of them test libraries
(bcrypt, secrets), not our code. See the review below.
"""

from datetime import datetime, timedelta, timezone

from app.services.auth import (
    hash_password,
    verify_password,
    generate_session_token,
    is_session_expired,
)


def test_hash_password_returns_a_hash_not_the_plaintext():
    hashed = hash_password("mysecretpassword")
    assert hashed != "mysecretpassword"
    assert len(hashed) > 20


def test_verify_password_accepts_correct_password():
    hashed = hash_password("correcthorse")
    assert verify_password("correcthorse", hashed) is True


def test_verify_password_rejects_wrong_password():
    hashed = hash_password("correcthorse")
    assert verify_password("wronghorse", hashed) is False


def test_generate_session_token_returns_hex_string():
    token = generate_session_token()
    assert isinstance(token, str)
    # 32 bytes = 64 hex characters
    assert len(token) == 64
    # must be valid hex
    int(token, 16)


def test_generate_session_token_is_not_predictable():
    tokens = {generate_session_token() for _ in range(100)}
    # all 100 tokens should be unique
    assert len(tokens) == 100


def test_session_not_expired_before_expiry_time():
    expires_at = datetime.now(timezone.utc) + timedelta(hours=1)
    assert is_session_expired(expires_at) is False


def test_session_expired_after_expiry_time():
    expires_at = datetime.now(timezone.utc) - timedelta(minutes=1)
    assert is_session_expired(expires_at) is True


# ── Agent's honest review ──────────────────────────────────────
#
# "These tests are correct but mostly trivial. You're testing
# that bcrypt works. bcrypt has been tested by thousands of
# people for 25 years. These tests have value as documentation
# but they don't catch bugs in your code because there's no
# logic to get wrong. The implementation is a one-line wrapper."
#
# Tests 1-3: Testing bcrypt, not our code.
# Tests 4-5: Testing secrets, not our code.
# Tests 6-7: Only tests with real value (boundary condition).
#
# The prompt was too implementation-focused. It told the agent
# what code to test rather than what could go wrong.
