-- 03_full_text_search.sql
-- Full-text search reference queries.
--
-- The fts column and GIN index are created in 01_setup.sql.
-- This file is a reference — not executed during init.
--
-- Example full-text search query using websearch_to_tsquery:

-- SELECT id, content
-- FROM documents
-- WHERE fts @@ websearch_to_tsquery('english', 'your search term here')
-- ORDER BY ts_rank(fts, websearch_to_tsquery('english', 'your search term here')) DESC
-- LIMIT 5;
