"""Unit tests for auth service — testing our logic, not library functions.

These tests were generated by asking the agent:
"Think about what could actually go wrong with the auth logic.
Focus on behaviours where a bug would be a security vulnerability.
Don't test library functions. If a test would still pass with a
completely different implementation, it's not testing anything useful."

6 tests. Every one proves a spec requirement or guards against a real risk.
None of them test library behaviour.
"""

from datetime import datetime, timedelta, timezone

from app.services.auth import (
    make_session_expiry,
    is_session_expired,
    generate_session_token,
    hash_password,
    verify_password,
)


def test_default_session_expiry_is_two_hours_from_now():
    before = datetime.now(timezone.utc)
    expires_at = make_session_expiry()
    after = datetime.now(timezone.utc)

    # should be ~2 hours from now
    assert expires_at >= before + timedelta(hours=2)
    assert expires_at <= after + timedelta(hours=2)


def test_session_expiry_respects_custom_duration():
    before = datetime.now(timezone.utc)
    expires_at = make_session_expiry(duration_minutes=30)
    after = datetime.now(timezone.utc)

    assert expires_at >= before + timedelta(minutes=30)
    assert expires_at <= after + timedelta(minutes=30)
    # must NOT be 2 hours — prove the override works
    assert expires_at < before + timedelta(hours=2)


def test_expired_session_is_rejected():
    """A session that expired 1 minute ago should not be treated as valid."""
    expired = datetime.now(timezone.utc) - timedelta(minutes=1)
    assert is_session_expired(expired) is True


def test_valid_session_is_accepted():
    """A session expiring in the future should be treated as valid."""
    valid = datetime.now(timezone.utc) + timedelta(hours=1)
    assert is_session_expired(valid) is False


def test_session_token_not_derived_from_user_data():
    """Tokens for the same user must differ — proving they're not based on user ID/email."""
    token_a = generate_session_token(user_id=1)
    token_b = generate_session_token(user_id=1)
    assert token_a != token_b


def test_wrong_password_never_verifies():
    """The core auth invariant: a wrong password must not grant access."""
    hashed = hash_password("real-password-123")
    assert verify_password("real-password-123", hashed) is True
    assert verify_password("wrong-password-456", hashed) is False
    assert verify_password("", hashed) is False
    assert verify_password("real-password-123 ", hashed) is False  # trailing space
